name: git push into personal repo to deploy using vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Push to another repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_REPO_TOKEN }}
          repository: ppyye/sorisonsoon-front
          branch: main
          force: true
